services:
  api:
    build: ./api
    container_name: dms-api
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - dms-network
    depends_on:
      - db

  # This service processes the background OCR jobs
  php-worker:
    build: ./api
    container_name: dms-worker
    restart: unless-stopped
    command: php artisan queue:work --timeout=300
    volumes:
      - ./api:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=database
    networks:
      - dms-network
    depends_on:
      - db
      - ocr

  spa:
    build: 
      context: ./spa
      dockerfile: Dockerfile
    container_name: dms-spa
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./spa:/app
    networks:
      - dms-network
    depends_on:
      - api

  ocr:
    build: 
      context: ./ocr
      dockerfile: Dockerfile
    container_name: dms-ocr
    restart: unless-stopped
    ports:
      - "5000:8000" 
    networks:
      - dms-network

  db:
    image: postgres:17-alpine
    container_name: dms-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dms-db-data:/var/lib/postgresql/data
    networks:
      - dms-network

volumes:
  dms-db-data:

networks:
  dms-network:
    driver: bridge